spring.address.datasource.url=jdbc:postgresql://localhost:5432/your_database_name
spring.address.datasource.username=postgres
spring.address.datasource.password=srinu
spring.address.datasource.driver-class-name=org.postgresql.Driver

spring.bill.datasource.url=jdbc:postgresql://localhost:5432/your_database_name
spring.bill.datasource.username=postgres
spring.bill.datasource.password=srinu
spring.bill.datasource.driver-class-name=org.postgresql.Driver

spring.category.datasource.url=jdbc:postgresql://localhost:5432/your_database_name
spring.category.datasource.username=postgres
spring.category.datasource.password=srinu
spring.category.datasource.driver-class-name=org.postgresql.Driver

spring.customer.datasource.url=jdbc:postgresql://localhost:5432/your_database_name
spring.customer.datasource.username=postgres
spring.customer.datasource.password=srinu
spring.customer.datasource.driver-class-name=org.postgresql.Driver

spring.foodCart.datasource.url=jdbc:postgresql://localhost:5432/your_database_name
spring.foodCart.datasource.username=postgres
spring.foodCart.datasource.password=srinu
spring.foodCart.datasource.driver-class-name=org.postgresql.Driver

spring.item.datasource.url=jdbc:postgresql://localhost:5432/your_database_name
spring.item.datasource.username=postgres
spring.item.datasource.password=srinu
spring.item.datasource.driver-class-name=org.postgresql.Driver

spring.orderItem.datasource.url=jdbc:postgresql://localhost:5432/your_database_name
spring.orderItem.datasource.username=postgres
spring.orderItem.datasource.password=srinu
spring.orderItem.datasource.driver-class-name=org.postgresql.Driver

#TODO-> JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect