spring.application.name=backend-netflix
server.port=3377

#TODO SECURITY JWT
server.compression.enabled=true
server.compression.mime-types=text/html,text/plain,text/xml,application/json,application/xml,text/javascript,text/css,application/javascript
server.compression.min-response-size=1024

#TODO ENABLE HTTPS 2.0
server.http2.enabled=true

#TODO TO RUN APPLICATION IN NATIVE --> ./gradlew nativeCompile | java -jar my-spring-app.jar --spring.profiles.active=dev
#TODO mvn spring-boot:run -Dspring.profiles.active=dev
#TODO ./gradlew bootRun --args='--spring.profiles.active=dev'
spring.profiles.active=dev
spring.profiles.default=none

spring.redis.host=localhost
spring.mail.username=dnsrinu143@gmail

spring.data.redis.host=localhost
spring.data.redis.port=6379

# application.properties example
spring.cache.type=redis
spring.redis.port=6379
spring.cache.redis.time-to-live=10m
spring.cache.cache-names=userCache,productCache

#https://medium.com/@javatechie/spring-boot-password-encryption-using-jasypt-e92eed7343ab
#Encrypt and Decrypt single String value::
#mvn jasypt:encrypt-value -Djasypt.encryptor.password=javatechie -Djasypt.plugin.value=Password
#mvn jasypt:decrypt-value -Djasypt.encryptor.password=javatechie -Djasypt.plugin.value=nObqvmVPYhxVaykMl09QVtGCQWjpd7al1RJhOsyz1eLkb6J2USMu9Fb//e4a6Vro
#mvn jasypt:encrypt -Djasypt.encryptor.password=javatechie
#java -Djasypt.encryptor.password=javatechie -jar spring-boot-application.jar

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url = jdbc:mysql://localhost:3306/javatechie
#spring.datasource.username = root
#spring.datasource.password = ENC(llo8Tfwc2cBLNAzjkksTk9dBj8tIwT3ZUHDQoFQm88D85qJTTY9doPcmQiN/Emtd)

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url = jdbc:mysql://localhost:3306/javatechie
#spring.datasource.username = root
#spring.datasource.password = DEC(Password)
