spring.application.name=backend-netflix
server.port=3371


#TODO-> Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/your_database_name
spring.datasource.username=postgres
spring.datasource.password=srinu
spring.datasource.driver-class-name=org.postgresql.Driver
#TODO-> JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dnsrinu143@gmail.com
spring.mail.password=(srinu1234aA@raju)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000

management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=env,beans
management.security.enabled=true
management.endpoints.enabled-by-default=false
management.endpoint.info.enabled=true
management.endpoints.jmx.exposure.include=health,info

#TODO SERVER ISSUE
spring.main.lazy-initialization=true

#TODO RATE LIMITING FOR APIS
resilience4j.ratelimiter.instances.basicRateLimiter.limit-for-period=5
resilience4j.ratelimiter.instances.basicRateLimiter.limit-refresh-period=1s
resilience4j.ratelimiter.instances.basicRateLimiter.timeout-duration=0

#TODO ENABLING HTTP 2
server.http2.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12

spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379
spring.cache.redis.time-to-live=10m
spring.cache.cache-names=userCache,productCache

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB

server.tomcat.max-swallow-size=-1
server.tomcat.max-http-from-post-size=-1

file.upload.video-dir=uploads/videos
file.upload.image-dir=uploads/videos